version: "3.9"
services:
  user:
    container_name: user
    build: ./user
    ports:
      - 5000:5000
    environment:
      - OTEL_SERVICE_NAME=user-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none

  todo:
    container_name: todo
    build: ./todo
    ports:
      - 5001:5000
    environment:
      - OTEL_SERVICE_NAME=todo-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 4317:4317     # accept OpenTelemetry Protocol (OTLP) over gRPC
      - 4318:4318     # accept OpenTelemetry Protocol (OTLP) over HTTP
      - 5775:5775/udp # (deprecated) accept zipkin.thrift over compact Thrift protocol (used by legacy clients only)
      - 5778:5778     # serve configs (sampling, etc.)
      - 6831:6831/udp # accept jaeger.thrift over Thrift-compact protocol 
      - 6832:6832/udp # accept jaeger.thrift over Thrift-binary protocol
      - 9411:9411     # Default endpoint for Zipkin receiver.
      - 16685:16685   # Starting GRPC server
      - 16686:16686   # Starting HTTP server
      - 14268:14268   # accept jaeger.thrift directly from clients
      - 14269:14269   # accept jaeger.thrift directly from clients
      - 14250:14250   # accept model.proto
