---
- name: System Check
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Collect memory usage
      command: free -h
      register: memory_output

    - name: Collect disk usage
      command: df -h
      register: disk_output

    - name: Show memory usage
      ansible.builtin.debug:
        var: memory_output.stdout_lines

    - name: Show disk usage
      ansible.builtin.debug:
        var: disk_output.stdout_lines

    - name: Print message
      ansible.builtin.debug:
        msg: "Script converted to a playbook!"