pipeline {
    agent any 
    
    environment {
        DOCKER_IMAGE_A = "service-a:${env.BUILD_ID}"
        DOCKER_IMAGE_B = "service-b:${env.BUILD_ID}"
    }

    stage('DEV - Testing') {
            steps {
                // Entra na pasta onde o projeto realmente está
                dir('devops/tokioschool/devops-microservices-project') {
                    sh '''
                    chmod +x run-tests.sh
                    ./run-tests.sh
                    '''
                }
            }
        

        stage('STG - Build & Orchestrate') {
            steps {
                dir('devops/tokioschool/devops-microservices-project') {
                    script {
                        sh 'docker compose build'
                        sh 'docker compose up -d'
                    }
                }
            }
        }

        stage('PRD - Deployment') {
            when {
                branch 'main'
            }
            steps {
                echo "Deploying to Production Environment..."
                sh 'docker compose up -d --force-recreate'
            }
        }
    }
    
    post {
        always {
            echo "Cleaning up workspace..."
        }
    }
}